name: nokhte
description: A new Flutter project.
publish_to: "none"

version: 0.8.0+108883306

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  add_2_calendar: ^3.0.1
  agora_rtc_engine: ^6.2.6
  audioplayers: ^5.2.0
  blur: ^3.1.0
  clipboard: ^0.1.3
  connectivity_plus: ^5.0.1
  const_date_time: ^1.0.3
  crypto: ^3.0.3
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_branch_sdk: ^7.0.2
  flutter_compass: ^0.8.0
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.3
  flutter_launcher_icons: ^0.13.1
  flutter_mobx: ^2.2.0
  flutter_modular: ^6.3.2
  flutter_platform_widgets: ^3.3.5
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.4
  haptic_feedback: ^0.4.2
  http: ^1.1.0
  intl: ^0.18.1
  matrix4_transform: ^2.0.1
  mesh_gradient: ^1.1.5
  mobx: ^2.2.1
  nokhte_backend:
    path: ../backend/dart
  path_drawing: ^1.0.1
  path_morph: ^1.1.1
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  posthog_flutter: ^3.2.0
  record: ^5.0.1
  record_darwin: ^1.0.1-beta.1
  sensors_plus: ^3.0.3
  share_plus: ^7.2.1
  sign_in_with_apple: ^5.0.0
  simple_animations: ^5.0.2
  simple_gradient_text: ^1.3.0
  supabase_flutter: ^1.10.9
  timezone: ^0.9.2
  touchable: ^1.0.2
  vibration: ^1.8.3

dev_dependencies:
  build_runner: ^2.3.3
  change_app_package_name: ^1.1.0
  clock: ^1.1.1
  fake_async: ^1.3.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  logger: ^2.0.2+1
  mobx_codegen: ^2.2.0
  mockito: ^5.4.0
  patrol: ^2.3.2

flutter:
  # uses-material-design: true
  assets:
    - .env
    - assets/app_logo.png
flutter_icons:
  image_path: "assets/app_logo.png"
  android: true
  ios: true
